### ISSUE TITLE
Tag traduzione ripristino password

### ISSUE THREAD

**Issue by Or-Laf** [MishFdM/MIUI_V9_Italy#100]
<img src="https://preview.ibb.co/iZaqAw/Screenshot_2017_11_02_18_19_27_865_lockscreen.png">
<img src="https://preview.ibb.co/ntjvcb/Screenshot_2017_11_02_18_19_25_886_lockscreen.png">

**Comment by MishFdM** [comment]
Corretto per prossima release.
