### ISSUE TITLE
Galleria + impostazioni home "schermata di blocco" 

### ISSUE THREAD

**Issue by Klezkk** [MishFdM/MIUI_V9_Italy#101]
La galleria va in crash con la lingua italiana su ultima dev.
+
Avete probabilmente tradotto il toggle Lock screen come sostantivo tra le impostazioni della home (touch lungo sullo sfondo - > Impostazioni) ma lì è usato come verbo + complemento oggetto (andrebbe tradotto come "Blocca lo schermo", inteso come impedisci modifiche al desktop finché è attivo il toggle, e non come "schermata di blocco" ).

**Comment by Or-Laf** [comment]
La traduzione "Schermata di blocco" attuale è già stata fixata nelle impostazioni della home.

Il fix verrà reso disponibile dalla prossima versione versione.
