### ISSUE TITLE
Traduzioni...

### ISSUE THREAD

**Issue by Or-Laf** [MishFdM/MIUI_V9_Italy#103]
<img src="https://preview.ibb.co/dBv97b/Screenshot_2017_11_05_12_31_23_205_com_miui_home.png">
<img src="https://preview.ibb.co/ivnYYG/Screenshot_2017_11_05_12_32_44_704_com_miui_securitycenter.png">
<img src="https://preview.ibb.co/eUr5fw/IMG_20171105_123029.jpg">
<img src="https://preview.ibb.co/gKs6nb/Screenshot_2017_11_05_13_09_24_824_com_miui_securitycenter.png">

**Comment by Or-Laf** [comment]
@ale8530

**Comment by Or-Laf** [comment]
Contapassi tutto attaccato.

**Comment by Or-Laf** [comment]
<img src="https://thumb.ibb.co/cCUEqw/Screenshot_2017_11_05_16_33_25_444_com_android_settings.png">

**Comment by ale8530** [comment]
L'ultimo screenshot servizio di Air ecc.. non può essere tradotto
