### ISSUE TITLE
Traduzione temi

### ISSUE THREAD

**Issue by Or-Laf** [MishFdM/MIUI_V9_Italy#117]
È possibile tradurre questa parte sulla vostra release?

<img src="https://preview.ibb.co/iO8PV6/Screenshot_2017_11_25_21_05_29_588_com_android_thememanager.png">

**Comment by ale8530** [comment]
Si devi dirmi esattamente le modifiche e le applichiamo

**Comment by Or-Laf** [comment]
I nomi dei temi ed il pulsante trova altro (quest'ultimo da verificare).

**Comment by ale8530** [comment]
Indicare nomi più appropriati :)
