### ISSUE TITLE
7.11.23 Lockscreen wrong translation

### ISSUE THREAD

**Issue by akyrey** [MishFdM/MIUI_V9_Italy#118]
Shortcuts added to left lockscreen isn't translated properly.
English version - Contacts, Calendar, Calculator, Notes.
Italian version: Mi Home, Mi Remote, Mi Pay, Scheda trasporto.

It should be: Contatti, Calendario, Calcolatrice, Note.

**Comment by ale8530** [comment]
Abbiamo bisogno di uno screenshot e scrivi in italiano.

Che rom monti?

**Comment by akyrey** [comment]
Scusami, ho la rom xiami eu weekly 7.11.23, device capricorn. Ho visto che hanno già postato lo screenshot e avete già chiuso la issue.
Grazie
