### ISSUE TITLE
Shortcuts a sinistra della lockscreen 

### ISSUE THREAD

**Issue by MatteoSevera** [MishFdM/MIUI_V9_Italy#119]
Nella mia versione 7.11.23, i nomi delle action nella lockscreen hanno una traduzione errata.
Contacts --> Mi Home
Calendar --> Mi Remote
Calculator --> Mi Pay
Notes --> Scheda trasporto
![image](https://user-images.githubusercontent.com/4078432/33382846-1d9e2e08-d522-11e7-9b3c-0a5fcad77d46.png)
![image](https://user-images.githubusercontent.com/4078432/33382880-34c9f60c-d522-11e7-893b-78f0d110b6bd.png)

**Comment by ale8530** [comment]
Già fissato-->https://github.com/MishFdM/MIUI_V9_Italy/issues/118
