### ISSUE TITLE
Traduzione ascolto brani da assistente

### ISSUE THREAD

**Issue by Or-Laf** [MishFdM/MIUI_V9_Italy#122]
<img src="https://preview.ibb.co/b2jenw/Screenshot_2017_12_01_23_27_16_570_com_miui_personalassistant.png">

**Comment by Or-Laf** [comment]
https://github.com/MishFdM/MIUI_V9_Italy/pull/123/files#diff-e9f58ce7d1ca786b97625a3ee4488fe2

**Comment by ale8530** [comment]
Si sistema con la Pr #123
