### ISSUE TITLE
problema aggiornamento 7.12.7 settimanale xiaomi.eu

### ISSUE THREAD

**Issue by Ilaby91** [MishFdM/MIUI_V9_Italy#127]
ho appena fatto l'ultimo aggiornamento di xiaomi.eu settimanale 7.12.7.
quando entro in menu applicazioni esce un errore sicurezza. se imposto la lingua in inglese il problema va via. mi hanno detto di inviare la segnalazione a voi. sono inesperta in materia e l'ho fatto. dicono sia un problema di traduzioni. ma leggendo il forum il problema c'è anche per la lingua olandese, portoghese e chissà quante altre. cosa si può fare? attendere il prossimo aggiornamento? il problema è dentro l'applicazione sicurezza cosi sembra.

**Comment by mario1944** [comment]
Confermo l'errore per mi4s

**Comment by ale8530** [comment]
Ho testato la xiaomi.eu mi4c ed effettivamente c'è un FC quando si va su impostazioni-->applicazioni, ma il problema non è da imputare a noi, in basso vedete lo screenshot, ho comunque avvisato ingbrzy di verificare

![screenshot_2017-12-08-13-32-09-503_com miui securitycenter](https://user-images.githubusercontent.com/6189615/33766247-f5f051c2-dc1c-11e7-9e75-d08cd3008eec.png)

**Comment by ale8530** [comment]
Mi sono confrontato con ingbrzy hanno costruito troppo presto le rom prima dei nostri commit, mi spiace, ma non riusciamo ad essere cosi immediati a volte,se costruiscono troppo presto non dipende da noi.

**Comment by ale8530** [comment]
stanno arrivando nuove rom mi conferma :)

**Comment by mario1944** [comment]
Grazie dell'informazione, avevo immaginato che non era colpa vostra.
Grazie del apprezzatissimo lavoro e cordiali saluti!

On December 8, 2017 1:48:42 PM GMT+01:00, ale8530 <notifications@github.com> wrote:
>stanno arrivando nuove rom mi conferma :)
>
>-- 
>You are receiving this because you commented.
>Reply to this email directly or view it on GitHub:
>https://github.com/MishFdM/MIUI_V9_Italy/issues/127#issuecomment-350255459

-- Inviato dal mio cellulare Android con K-9 Mail.
