### ISSUE TITLE
buon note 3

### ISSUE THREAD

**Issue by abruno1970** [MishFdM/MIUI_V9_Italy#133]
Note 3
Ci sono un paio di problemi gravi 
Ricezione wifi e cellulare peggiorata notevolmente .
Ridotte il numero di icone nella home e nelle altre pagine non è più possibile scegliere la griglia 5x6

**Comment by Or-Laf** [comment]
Questa è la pagina delle traduzioni, per discutere di altre problematiche bisogna usare il forum nell'apposita sezione.

**Comment by abruno1970** [comment]
Perfetto grazie.
