### ISSUE TITLE
traduzione mi cloud 6.0.1

### ISSUE THREAD

**Issue by bugrider87** [MishFdM/MIUI_V9_Italy#139]
![screenshot_2017-12-25-08-57-49-959_com miui cloudservice](https://user-images.githubusercontent.com/25429906/34355459-b900cd92-ea35-11e7-97b0-ad45cc287097.png)

tradurre aperto con attivo, chiuso con disattivo

nel disegno "corona" viene visualizzato il tipo account vip o normale tradure "none" con nessuno oppure con standard

in fine all important things in one place va tradotto con tutte le cose importanti in un unico posto

**Comment by ale8530** [comment]
Tutto da server xiaomi non dipende da noi

**Comment by Or-Laf** [comment]
@ale8530 Non tutto...

https://github.com/MishFdM/MIUI_V9_Italy/pull/140
