### ISSUE TITLE
doppia notifica whatsapp

### ISSUE THREAD

**Issue by Ilaby91** [MishFdM/MIUI_V9_Italy#144]
sicuramente non è un problema di traduzioni ma lo segnalo anche qui. con l'aggiornamento 7.12.28 quando arriva un singolo messaggio su whatsapp compaiono 2 icone di notifica. è fastidioso. leggevo che anche per gmail è lo stesso. ed il problema è per tutti i modelli. ingbrzy è già a conoscenza credo.

**Comment by ale8530** [comment]
Non centra nulla con noi chiuso
