### ISSUE TITLE
Fix traduzione

### ISSUE THREAD

**Issue by Or-Laf** [MishFdM/MIUI_V9_Italy#150]
<img src="https://preview.ibb.co/k6iaXR/Screenshot_2018_01_12_12_21_03_987_com_android_settings.jpg">

**Comment by ale8530** [comment]
Riscontri ancora questo problema dopo l'aggiornamento 8.1.11?

**Comment by Or-Laf** [comment]
So, sull'8.1.11 c'è ancora...
