### ISSUE TITLE
Crash Introduzione iniziale

### ISSUE THREAD

**Issue by Antonpet97** [MishFdM/MIUI_V9_Italy#157]
Nella 8.1.18 ho avuto il problema del crash dell'introduzione iniziale dove si settano i vari parametri prima usare la MIUI che mi ha costretto a cambiare Rom, purtroppo lo screenshot non ce l'ho, ma il problema è presente!

**Comment by ale8530** [comment]
Se hai la miui.it abbiamo rilasciato la fix.

**Comment by Antonpet97** [comment]
Dove, non lo trovo.

**Comment by Antonpet97** [comment]
Cioè in che senso con il fix, perché io ho scaricato ieri la MIUI.it appena flashata, da subito ha avuto crash, quindi dov'è reperibile il fix di cui parli?

**Comment by ale8530** [comment]
Intanto,che dispositivo hai

**Comment by Antonpet97** [comment]
Mi Note 3

**Comment by ale8530** [comment]
versione...developer o stabile

**Comment by Antonpet97** [comment]
Developer

**Comment by ale8530** [comment]
Per ora non riscontriamo bug segnalati, aspetta prossima versione se non va segnali sul forum e non qui

**Comment by Antonpet97** [comment]
Ok
