### ISSUE TITLE
Traduzioni Cit.apk

### ISSUE THREAD

**Issue by Or-Laf** [MishFdM/MIUI_V9_Italy#177]
<img src="https://preview.ibb.co/bZCHun/Screenshot_2018_03_27_01_01_50_698_com_miui_cit.jpg">

<img src="https://preview.ibb.co/hxkyjn/IMG_20180326_214002.jpg">

<img src="https://preview.ibb.co/jFs0x7/Screenshot_2018_03_26_21_37_18_739_com_miui_cit.jpg">

<img src="https://preview.ibb.co/fUtjPn/Screenshot_2018_03_26_21_42_14_801_com_miui_cit.jpg">

**Comment by Or-Laf** [comment]
Problema esterno trovato:

<img src="https://preview.ibb.co/dB29qS/Screenshot_2018_03_27_01_40_52_457_com_android_settings.jpg">

**Comment by ale8530** [comment]
"COMPLETED" non esiste stringa

**Comment by ale8530** [comment]
Ciò che non è stato fissato purtroppo al momento non può essere sistemato a causa di alcuni bug dovuti al software di compilazione, ho già provveduto a contattare lo sviluppatore per la risoluzione del problema
