### ISSUE TITLE
Mancata traduzione

### ISSUE THREAD

**Issue by bugrider87** [MishFdM/MIUI_V9_Italy#77]
Galleria mancata traduzione ( o MIUI lab )

http://i68.tinypic.com/2me7sqx.png

http://i63.tinypic.com/50mo1h.png

La barra di ricerca risulta in lingua cinese

**Comment by ale8530** [comment]
Avevo già adocchiato questo problema, ma stavo aspettando un fix da parte di xiaomi, perchè successivamente apre un menu pieno di cinese

**Comment by ale8530** [comment]
Per eliminare il problema disattivare "Trova foto nella Galleria" da Miui Lab, questa è una funzione sperimentale quindi è normale che sia cinese.

**Comment by bugrider87** [comment]
Ok

**Comment by ale8530** [comment]
Per il momento nessun riscontro sulle stringhe forse è via Micloud e non si può tradurre

**Comment by ale8530** [comment]
Mi sono confrontato anche con gli amici di xiaomi.eu e confermano la mia ipotesi non è possibile tradurre al momento questo menu.

Chiudo issue :)
