### ISSUE TITLE
Traduzione diagnostica

### ISSUE THREAD

**Issue by Or-Laf** [MishFdM/MIUI_V9_Italy#83]
<img src="https://preview.ibb.co/cxEXt6/Screenshot_2017_10_20_01_07_01_100_com_miui_cit.png">
<img src="https://preview.ibb.co/nmuyY6/Screenshot_2017_10_20_01_10_08_980_com_miui_cit.png">
<img src="https://preview.ibb.co/caswLm/Screenshot_2017_10_20_01_07_19_481_com_miui_cit.png"><img src="https://preview.ibb.co/cdx7RR/Screenshot_2017_10_20_01_07_59_155_com_miui_cit.png">
<img src="https://preview.ibb.co/doFi0m/Screenshot_2017_10_20_01_09_43_461_com_miui_cit.png"><img src="https://preview.ibb.co/hwwqfm/Screenshot_2017_10_20_01_07_29_175_com_miui_cit.png"
<img src="https://preview.ibb.co/bMPe6R/Screenshot_2017_10_20_01_17_17_923_com_miui_cit.png">
<img src="https://preview.ibb.co/eSM3Y6/Screenshot_2017_10_20_01_19_23_747_com_miui_cit.png">
<img src="https://preview.ibb.co/d6dHt6/Screenshot_2017_10_20_01_17_50_786_com_miui_cit.png">

**Comment by ale8530** [comment]
Se vuoi puoi aiutarci tu, abbiamo allineato la situazione proprio ieri, ma questo apk è rimasto indietro :)

**Comment by Or-Laf** [comment]
@ale8530

Quando posso ci do un occhiata...

**Comment by MishFdM** [comment]
Si tratta di Cit.apk è l'unico incompleto ad oggi, ovviamente abbiamo dato priorità a tutti gli altri che influiscono maggiormente nell'esperienza utente.
