### ISSUE TITLE
Traduzione Antivirus

### ISSUE THREAD

**Issue by Or-Laf** [MishFdM/MIUI_V9_Italy#84]
<img src="https://preview.ibb.co/ddMnRR/Screenshot_2017_10_20_11_05_18_961_com_miui_securitycenter.png">

**Comment by ale8530** [comment]
Pulire i dati applicazione e tornano tradotte

**Comment by Or-Laf** [comment]
@ale8530 Ok andato.

Qui invece proprio non c'é santo che tenga...

<img src="https://thumb.ibb.co/gokmLm/Screenshot_2017_10_20_11_45_37_699_com_android_settings.png">
