### ISSUE TITLE
Errori traduzione

### ISSUE THREAD

**Issue by bugrider87** [MishFdM/MIUI_V9_Italy#91]
Dispositivo xiaomi redmi note 3 special edition
<a href="http://it.tinypic.com?ref=2nubsg" target="_blank"><img src="http://i64.tinypic.com/2nubsg.png" border="0" alt="Image and video hosting by TinyPic"></a>

App sicurezza pulizia Deep clean
Si legge il codice

<a href="http://it.tinypic.com?ref=2qdxz60" target="_blank"><img src="http://i65.tinypic.com/2qdxz60.png" border="0" alt="Image and video hosting by TinyPic"></a>

Impostazioni della home screan
Scrermata di blocco non esatta dovrebbe essere blocco applicazioni o blocca spazi vuoti

<a href="http://it.tinypic.com?ref=b4j2wi" target="_blank"><img src="http://i63.tinypic.com/b4j2wi.png" border="0" alt="Image and video hosting by TinyPic"></a>

**Comment by ale8530** [comment]
A parte schermata di blocco è già tutto fissato, ormai per prossima release

**Comment by Or-Laf** [comment]
https://github.com/MishFdM/MIUI_V9_Italy/pull/92

**Comment by bugrider87** [comment]
ok perfetto :)

**Comment by ale8530** [comment]
Issue risolta
